[package]
name = "rustengan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
serde = { verion = "1", features = ["derive"]}
serde_json = "1"
ulid = "1.1.2"
